name:                servant-demo
version:             0.1.0.0
github:              "akirak/servant-demo"
license:             BSD3
author:              "Akira Komamura"
maintainer:          "akira.komamura@gmail.com"
copyright:           "2020 Akira Komamura"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akirak/servant-demo#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  servant-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-demo

tests:
  servant-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - servant-demo
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
